/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controldor.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.annotation.Resource;
import javax.swing.JOptionPane;

/**
 *
 * @author BrymOzl
 */
public class CrearPersona extends javax.swing.JPanel {

    //ControladorDatosPersonales cDP =  new ControladorDatosPersonales();
    private ControladorCliente cDP;
    /**
     * Creates new form CrearP
     */
    public CrearPersona(ControladorCliente cDP) {
        initComponents();
        this.cDP = cDP;
        codigoTxt.setEditable(false);
        cDP.contar(codigoTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoJlb = new javax.swing.JLabel();
        cedulaJlb = new javax.swing.JLabel();
        nombreJlb = new javax.swing.JLabel();
        appellidoJlb = new javax.swing.JLabel();
        telefonoJlb = new javax.swing.JLabel();
        direccionJlb = new javax.swing.JLabel();
        pesoJlb = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        cedulaTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        telefonoTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        pesoTxt = new javax.swing.JTextField();
        crearBnt = new javax.swing.JButton();
        limpiarBnt = new javax.swing.JButton();
        cancelarBnt = new javax.swing.JButton();

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1InternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("Crear Persona");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 24, -1, -1));

        codigoJlb.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        codigoJlb.setForeground(new java.awt.Color(0, 204, 204));
        codigoJlb.setText("Codigo:");
        jPanel1.add(codigoJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 81, -1, -1));

        cedulaJlb.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cedulaJlb.setForeground(new java.awt.Color(0, 204, 204));
        cedulaJlb.setText("Cedula:");
        jPanel1.add(cedulaJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 135, -1, -1));

        nombreJlb.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        nombreJlb.setForeground(new java.awt.Color(0, 204, 204));
        nombreJlb.setText("Nombre:");
        jPanel1.add(nombreJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 189, -1, -1));

        appellidoJlb.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        appellidoJlb.setForeground(new java.awt.Color(0, 204, 204));
        appellidoJlb.setText("Apellido:");
        jPanel1.add(appellidoJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 243, -1, -1));

        telefonoJlb.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        telefonoJlb.setForeground(new java.awt.Color(0, 204, 204));
        telefonoJlb.setText("Telefono:");
        jPanel1.add(telefonoJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 297, -1, -1));

        direccionJlb.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        direccionJlb.setForeground(new java.awt.Color(0, 204, 204));
        direccionJlb.setText("Direccion:");
        jPanel1.add(direccionJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 351, -1, -1));

        pesoJlb.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        pesoJlb.setForeground(new java.awt.Color(0, 204, 204));
        pesoJlb.setText("Credito:");
        jPanel1.add(pesoJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 405, -1, -1));

        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 72, 57, 36));
        jPanel1.add(cedulaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 126, 178, 36));
        jPanel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 180, 178, 36));
        jPanel1.add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 234, 178, 36));
        jPanel1.add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 288, 178, 36));
        jPanel1.add(direccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 342, 178, 36));
        jPanel1.add(pesoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 396, 88, 36));

        crearBnt.setText("Crear");
        crearBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBntActionPerformed(evt);
            }
        });
        jPanel1.add(crearBnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 450, -1, -1));

        limpiarBnt.setText("Limpiar");
        limpiarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBntActionPerformed(evt);
            }
        });
        jPanel1.add(limpiarBnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 450, -1, -1));

        cancelarBnt.setText("Cancelar");
        cancelarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBntActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarBnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 450, -1, -1));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBntActionPerformed
        cedulaTxt.setText("");
        nombreTxt.setText("");
        apellidoTxt.setText("");
        direccionTxt.setText("");
        telefonoTxt.setText("");
        pesoTxt.setText("");
    }//GEN-LAST:event_limpiarBntActionPerformed

    private void cancelarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBntActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBntActionPerformed

    private void jInternalFrame1InternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1InternalFrameClosed
        this.setVisible(false);
    }//GEN-LAST:event_jInternalFrame1InternalFrameClosed

    private void crearBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBntActionPerformed
        if (cedulaTxt.getText().equals("") || nombreTxt.getText().equals("") || apellidoTxt.getText().equals("") || telefonoTxt.getText().equals("") || direccionTxt.getText().equals("") || pesoTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el Campo Vacio");
        } else {
            Cliente dp = new Cliente();
            dp.setCodigo(Integer.valueOf(codigoTxt.getText()));
            dp.setCedula(cedulaTxt.getText());
            dp.setNombre(nombreTxt.getText());
            dp.setApellido(apellidoTxt.getText());
            dp.setTelefono(telefonoTxt.getText());
            dp.setDireccion(direccionTxt.getText());
            dp.setPeso(Double.valueOf(pesoTxt.getText()));
            cDP.crear(dp);

            cDP.contar(codigoTxt);

            cedulaTxt.setText("");
            nombreTxt.setText("");
            apellidoTxt.setText("");
            telefonoTxt.setText("");
            direccionTxt.setText("");
            pesoTxt.setText("");

            JOptionPane.showMessageDialog(this, "Cliente Creada");
        }
    }//GEN-LAST:event_crearBntActionPerformed

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JLabel appellidoJlb;
    private javax.swing.JButton cancelarBnt;
    private javax.swing.JLabel cedulaJlb;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JLabel codigoJlb;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JButton crearBnt;
    private javax.swing.JLabel direccionJlb;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiarBnt;
    private javax.swing.JLabel nombreJlb;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel pesoJlb;
    private javax.swing.JTextField pesoTxt;
    private javax.swing.JLabel telefonoJlb;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables

    public void cambiar_Idioma(Locale locale){
        ResourceBundle mensajes = ResourceBundle.getBundle("ec.edu.ups.mensajes.mensajes",locale);
        String c=mensajes.getString("etiqueta_codigo");
        codigoJlb.setText(c);
        c="";
        c=mensajes.getString("etiqueta_cedula");
        cedulaJlb.setText(c);
        c="";
        c=mensajes.getString("etiqueta_nombre");
        nombreJlb.setText(c);
        c="";
        c=mensajes.getString("etiqueta_apellido");
        appellidoJlb.setText(c);
        c="";
        c=mensajes.getString("etiqueta_telefono");
        telefonoJlb.setText(c);
        c="";
        c=mensajes.getString("etiqueta_direccion");
        direccionJlb.setText(c);
        c="";
        c=mensajes.getString("etiqueta_peso");
        pesoJlb.setText(c);
        c="";
        c=mensajes.getString("boton_crear");
        crearBnt.setText(c);
        c="";
        c=mensajes.getString("boton_limpiar");
        limpiarBnt.setText(c);
        c="";
        c=mensajes.getString("boton_cancelar");
        cancelarBnt.setText(c);
        c="";
        c=mensajes.getString("etiqueta_titulo");
        jLabel1.setText(c);
    }
    
    /*public void idioma(){
        if(ventanaProncipal.idiomaIngles(i)==1){
            cambiar_Idioma(locale);
        }else
        if(ventanaProncipal.idiomaEspanol(e)==1){
            cambiar_Idioma(localeepa);
        }
    }*/
}
