/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controldor.ControladorLibro;
import ec.edu.ups.modelo.Libro;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BrymOzl
 */
public class ListarLibro extends javax.swing.JFrame {
    private ControladorLibro cP;
    /**
     * Creates new form ListarPais
     */
    public ListarLibro(ControladorLibro cP) {
        initComponents();
        this.cP=cP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloListarPaisJbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaisJtbl = new javax.swing.JTable();
        listarBnt = new javax.swing.JButton();
        cancelarBnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloListarPaisJbl.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tituloListarPaisJbl.setText("Lista de Libros");

        tablaPaisJtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Autor", "Edicion", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaPaisJtbl);

        listarBnt.setText("LISTAR");
        listarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBntActionPerformed(evt);
            }
        });

        cancelarBnt.setText("CANCELAR");
        cancelarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listarBnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarBnt))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(tituloListarPaisJbl)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloListarPaisJbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarBnt)
                    .addComponent(cancelarBnt))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBntActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaPaisJtbl.getModel();
        for (int i = 0; i < tablaPaisJtbl.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        for (Libro p : cP.listarPais()) {
            Object[] rowData = {p.getCodigo_P(), p.getTitulo(), p.getAutor(), p.getEdicion(), p.getPrecio()};
            modelo.addRow(rowData);
        }
        tablaPaisJtbl.setModel(modelo);
    }//GEN-LAST:event_listarBntActionPerformed

    private void cancelarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBntActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBntActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBnt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarBnt;
    private javax.swing.JTable tablaPaisJtbl;
    private javax.swing.JLabel tituloListarPaisJbl;
    // End of variables declaration//GEN-END:variables
}
