/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controldor.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BrymOzl
 */
public class ListarPersonas extends javax.swing.JFrame {

    private ControladorCliente cP;

    /**
     * Creates new form ListarPersonas
     */
    public ListarPersonas(ControladorCliente cP) {
        initComponents();
        this.cP = cP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJtbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        listarBnt = new javax.swing.JButton();
        salirBnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        tablaJtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cedula", "Nombres", "Apellidos", "Tellefono", "Direccion", "Credito"
            }
        ));
        jScrollPane1.setViewportView(tablaJtbl);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Personas");

        listarBnt.setText("Listar Personas");
        listarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBntActionPerformed(evt);
            }
        });

        salirBnt.setText("Salir");
        salirBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(435, Short.MAX_VALUE)
                        .addComponent(listarBnt)
                        .addGap(439, 439, 439)
                        .addComponent(salirBnt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarBnt)
                    .addComponent(salirBnt))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBntActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirBntActionPerformed

    private void listarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBntActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaJtbl.getModel();
        for (int i = 0; i < tablaJtbl.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        for (Cliente dp : cP.listarTodo()) {
            Object[] rowData = {dp.getCodigo(), dp.getCedula(), dp.getNombre(), dp.getApellido(), dp.getTelefono(), dp.getDireccion(), dp.getPeso()};
            modelo.addRow(rowData);
        }
        tablaJtbl.setModel(modelo);
    }//GEN-LAST:event_listarBntActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarBnt;
    private javax.swing.JButton salirBnt;
    private javax.swing.JTable tablaJtbl;
    // End of variables declaration//GEN-END:variables
}
